const path = require("path");
const fs = require("fs");
const Pattern = require("./pattern").Pattern;
const config = require("./configParser").config;
const saveSTL = require("./saveSTL");
var cfg = new config().get_as_object();
var f = JSON.parse(fs.readFileSync(path.resolve(__dirname, "test0.fold"), 'utf-8'));
var pattern = new Pattern(cfg, f);
var obj = saveSTL.objFileContent(pattern);
console.log(obj);